// GENERATED by Chief. This connection runs in Eve's trusted host process.
import { defineMcpClientConnection } from "eve/connections";

const configuredUrl = process.env.EXECUTOR_MCP_URL;
const url = configuredUrl ?? "https://executor.invalid/mcp";

export default defineMcpClientConnection({
  url,
  description:
    "Connected marketing integrations and durable Chief workspace tools.",
  auth: {
    getToken: async () => {
      if (!configuredUrl)
        throw new Error("EXECUTOR_MCP_URL is required to call Executor.");
      const token = process.env.EXECUTOR_MCP_TOKEN;
      if (!token)
        throw new Error("EXECUTOR_MCP_TOKEN is required to call Executor.");
      return { token };
    },
  },
});
