import type { ChannelApiOperation } from "./types";

export const channelApiPrinciples = [
  "Archive is the normal cleanup path. It preserves history and can be reversed.",
  "Permanent deletion is owner-reviewed and never happens as a hidden agent side effect.",
  "Core channels start locked. Owners decide where agents may change metadata, membership, workstream state, or lifecycle.",
  "Create requests accept an operation key, so retries return the original channel instead of making duplicates.",
  "Updates accept an expected version, so an agent cannot silently overwrite a newer human edit.",
  "Every management action is recorded in channel activity with the responsible human or agent.",
] as const;

export const channelApiOperations: readonly ChannelApiOperation[] = [
  {
    operationId: "channels.list",
    method: "GET",
    path: "/local-tools/channels",
    group: "Discover",
    summary: "List channels",
    description:
      "Lists visible workspace channels with lifecycle, membership, policy and feature-work metadata. Archived channels are opt-in.",
    permission: "Workspace member",
    toolPermission: "channels.read",
    reversible: true,
  },
  {
    operationId: "channels.get",
    method: "GET",
    path: "/local-tools/channels/{channelId}",
    group: "Discover",
    summary: "Get a channel",
    description:
      "Returns one channel by stable id or slug, including the current version used for conflict-safe updates.",
    permission: "Workspace member",
    toolPermission: "channels.read",
    reversible: true,
  },
  {
    operationId: "channels.create",
    method: "POST",
    path: "/local-tools/channels",
    group: "Lifecycle",
    summary: "Create a channel",
    description:
      "Creates a standard or feature channel, resolves its initial member roster before writing, and safely deduplicates retries with operationKey.",
    permission: "Workspace member",
    toolPermission: "channels.create",
    reversible: true,
  },
  {
    operationId: "channels.update",
    method: "PATCH",
    path: "/local-tools/channels/{channelId}",
    group: "Lifecycle",
    summary: "Update channel details",
    description:
      "Updates metadata or feature-work state without changing the stable channel slug. expectedVersion prevents lost updates.",
    permission: "Channel management enabled",
    toolPermission: "channels.update",
    reversible: true,
  },
  {
    operationId: "channels.archive",
    method: "POST",
    path: "/local-tools/channels/{channelId}/archive",
    group: "Lifecycle",
    summary: "Archive a channel",
    description:
      "Closes an active channel while retaining its messages, members and audit history. Protected channels cannot be archived by agents.",
    permission: "Channel management enabled",
    toolPermission: "channels.archive",
    reversible: true,
  },
  {
    operationId: "channels.unarchive",
    method: "POST",
    path: "/local-tools/channels/{channelId}/unarchive",
    group: "Lifecycle",
    summary: "Restore an archived channel",
    description:
      "Returns an archived channel to active work without recreating its history or membership.",
    permission: "Channel management enabled",
    toolPermission: "channels.archive",
    reversible: true,
  },
  {
    operationId: "channels.join",
    method: "POST",
    path: "/local-tools/channels/{channelId}/join",
    group: "Members",
    summary: "Join a channel",
    description:
      "Adds the calling member to an active public channel. Private channels require an invitation.",
    permission: "Workspace member",
    toolPermission: "members.manage",
    reversible: true,
  },
  {
    operationId: "channels.leave",
    method: "POST",
    path: "/local-tools/channels/{channelId}/leave",
    group: "Members",
    summary: "Leave a channel",
    description:
      "Removes the calling member from the channel while preserving work and history.",
    permission: "Channel member",
    toolPermission: "members.manage",
    reversible: true,
  },
  {
    operationId: "channels.members.list",
    method: "GET",
    path: "/local-tools/channels/{channelId}/members",
    group: "Members",
    summary: "List channel members",
    description:
      "Lists participating humans and agents with their effective roles.",
    permission: "Workspace member",
    toolPermission: "members.read",
    reversible: true,
  },
  {
    operationId: "channels.members.add",
    method: "POST",
    path: "/local-tools/channels/{channelId}/members",
    group: "Members",
    summary: "Add members",
    description:
      "Adds existing workspace people or agents, then records who invited them in the channel. Use an idempotency key when retrying.",
    permission: "Channel management enabled",
    toolPermission: "members.manage",
    reversible: true,
  },
  {
    operationId: "channels.members.remove",
    method: "DELETE",
    path: "/local-tools/channels/{channelId}/members/{memberId}",
    group: "Members",
    summary: "Remove a member",
    description:
      "Removes a human or agent from the channel without deleting their prior messages or workspace identity.",
    permission: "Channel management enabled",
    toolPermission: "members.manage",
    reversible: true,
  },
  {
    operationId: "channels.messages.post",
    method: "POST",
    path: "/local-tools/channels/{channelId}/messages",
    group: "Messages",
    summary: "Post a message",
    description:
      "Publishes a concise progress update, decision request, result or pull-request link as the calling agent. Ordinary working output stays private.",
    permission: "Channel member",
    toolPermission: "messages.send",
    reversible: false,
  },
  {
    operationId: "channels.messages.list",
    method: "GET",
    path: "/local-tools/channels/{channelId}/messages",
    group: "Messages",
    summary: "List messages",
    description:
      "Returns a cursor-paginated channel timeline. Reactions are included with their target messages rather than mixed into the timeline.",
    permission: "Channel member",
    toolPermission: "messages.read",
    reversible: true,
  },
  {
    operationId: "channels.messages.get",
    method: "GET",
    path: "/local-tools/channels/{channelId}/messages/{messageId}",
    group: "Messages",
    summary: "Get a message",
    description:
      "Returns one visible message with its author, thread metadata, reactions and current edit state.",
    permission: "Channel member",
    toolPermission: "messages.read",
    reversible: true,
  },
  {
    operationId: "channels.messages.replies",
    method: "GET",
    path: "/local-tools/channels/{channelId}/messages/{messageId}/replies",
    group: "Messages",
    summary: "List thread replies",
    description:
      "Returns the root and cursor-paginated replies for one thread without leaking replies into the channel timeline.",
    permission: "Channel member",
    toolPermission: "messages.read",
    reversible: true,
  },
  {
    operationId: "channels.messages.search",
    method: "GET",
    path: "/local-tools/messages/search",
    group: "Messages",
    summary: "Search messages",
    description:
      "Searches visible channel and direct-message history with optional channel, author and time filters.",
    permission: "Workspace member",
    toolPermission: "messages.read",
    reversible: true,
  },
  {
    operationId: "channels.messages.update",
    method: "PATCH",
    path: "/local-tools/channels/{channelId}/messages/{messageId}",
    group: "Messages",
    summary: "Edit a message",
    description:
      "Edits a message authored by the caller. expectedVersion prevents a late edit from overwriting a newer one.",
    permission: "Channel member",
    toolPermission: "messages.manage",
    reversible: true,
  },
  {
    operationId: "channels.messages.delete",
    method: "DELETE",
    path: "/local-tools/channels/{channelId}/messages/{messageId}",
    group: "Messages",
    summary: "Delete a message",
    description:
      "Replaces an authored message with a durable tombstone while retaining its thread shape and owner-visible audit history.",
    permission: "Channel member",
    toolPermission: "messages.manage",
    reversible: false,
  },
  {
    operationId: "channels.reactions.list",
    method: "GET",
    path: "/local-tools/channels/{channelId}/messages/{messageId}/reactions",
    group: "Reactions",
    summary: "List reactions",
    description: "Lists reactions grouped by emoji and member on one message.",
    permission: "Channel member",
    toolPermission: "messages.read",
    reversible: true,
  },
  {
    operationId: "channels.reactions.add",
    method: "POST",
    path: "/local-tools/channels/{channelId}/messages/{messageId}/reactions",
    group: "Reactions",
    summary: "Add a reaction",
    description:
      "Adds one idempotent emoji reaction as the calling human or agent.",
    permission: "Channel member",
    toolPermission: "messages.send",
    reversible: true,
  },
  {
    operationId: "channels.reactions.remove",
    method: "DELETE",
    path: "/local-tools/channels/{channelId}/messages/{messageId}/reactions/{emoji}",
    group: "Reactions",
    summary: "Remove a reaction",
    description:
      "Removes the caller's matching reaction without changing anybody else's reactions.",
    permission: "Channel member",
    toolPermission: "messages.send",
    reversible: true,
  },
  {
    operationId: "channels.activity.list",
    method: "GET",
    path: "/local-tools/channels/{channelId}/activity",
    group: "Governance",
    summary: "Read management activity",
    description:
      "Returns the durable audit trail for lifecycle, membership, policy and cross-channel posting actions.",
    permission: "Workspace member",
    toolPermission: "channels.read",
    reversible: true,
  },
  {
    operationId: "channels.deletion.request",
    method: "POST",
    path: "/local-tools/channels/{channelId}/deletion-request",
    group: "Governance",
    summary: "Request permanent deletion",
    description:
      "Raises a clearly explained owner action. Agents cannot permanently erase a channel or its history themselves.",
    permission: "Channel management enabled",
    toolPermission: "channels.archive",
    reversible: true,
  },
];
