import type { Playbook } from "./playbook-types";
import { createMeasurementExperimentsPlaybook } from "./measurement-experiments-playbook";
import { INTEGRATIONS, sharedGuardrails } from "./playbook-catalog-foundations";

export const primaryPlaybooks: Playbook[] = [
  createMeasurementExperimentsPlaybook({
    integrations: [
      INTEGRATIONS.github,
      INTEGRATIONS.vercel,
      INTEGRATIONS.analytics,
      INTEGRATIONS.posthog,
    ],
    sharedGuardrails,
  }),
  {
    id: "growth-brief",
    title: "Growth report",
    summary: "Changes, causes, and next steps.",
    task: "Compile a growth report from our connected analytics: what changed, why it matters, and the next action for each insight.",
    agentId: "analyst",
    categories: ["Conversion"],
    integrations: [INTEGRATIONS.analytics, INTEGRATIONS.posthog],
    goal: "Turn recent acquisition and product usage data into a short weekly decision brief.",
    inputs: [
      "A defined reporting window and comparison period.",
      "At least one current analytics source with dated metrics.",
      "The conversion or business outcome the report should optimize for.",
    ],
    workflow: [
      "Compare the latest complete period with the previous equivalent period.",
      "Find the largest meaningful changes, then check whether channel, page, campaign, or product data explains them.",
      "Separate observed evidence from likely explanations.",
      "Choose one practical next action for every reported insight.",
    ],
    deliverables: [
      "A concise executive summary.",
      "Up to three evidence-backed insights with what changed, why it matters, and the next action.",
      "Charts or tables for the comparisons that materially support the analysis.",
      "A short data-quality note covering unavailable or stale sources.",
    ],
    accessNotes: [
      "Use Google Analytics for acquisition and site behavior, then PostHog for product events when both are connected.",
      "If only a cached or single-metric snapshot exists, report that limitation and avoid causal claims.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "buying-signals",
    title: "Find buying signals",
    summary: "People actively describing the problem you solve.",
    task: "Find new public conversations where people in our ideal customer profile are actively describing the problem we solve. Save only strong matches with the source, evidence, and a useful reply or outreach angle for my review.",
    agentId: "prospector",
    categories: ["Find customers"],
    integrations: [
      INTEGRATIONS.reddit,
      INTEGRATIONS.x,
      INTEGRATIONS.linkedin,
      INTEGRATIONS.facebook,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
    ],
    goal: "Surface people and companies with a timely, observable reason to consider the product.",
    inputs: [
      "An ideal customer profile with exclusions, geography, and business type.",
      "Concrete problem phrases, alternatives, and high-intent behaviors.",
      "A recency window and minimum evidence threshold.",
    ],
    workflow: [
      "Translate the ideal customer profile into concrete pain, intent, and timing signals.",
      "Search each available channel separately using language and formats native to that community.",
      "On Facebook and Instagram, prioritize connected Page or professional-account comments, mentions, hashtags, and approved public Page data.",
      "On TikTok, use connected-account comments and videos unless eligible public-research access is explicitly available.",
      "Reject vague matches, stale posts, recruiters, competitors, and unsupported guesses.",
      "Rank qualified signals by fit, urgency, and how naturally the product can help.",
    ],
    deliverables: [
      "A table of qualified people or companies with source links and quoted evidence.",
      "The signal, fit rationale, confidence, and recommended next step for each match.",
      "A value-first reply or outreach angle for review, never an automatically sent message.",
    ],
    accessNotes: [
      "Reddit, X, and accessible public web results can support broad discovery, subject to their terms and available tools.",
      "Meta APIs do not provide unrestricted search across personal Facebook or Instagram accounts.",
      "TikTok commercial integrations normally expose the authorized account; broad public-content querying is restricted to approved research use cases.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "social-account-setup",
    title: "Set up social accounts",
    summary: "Find a consistent handle and prepare each profile.",
    task: "Find a distinctive, brand-aligned social handle we can use consistently, verify the strongest options across our priority platforms, and prepare the accounts for setup. Do not claim a handle or create an account without my approval.",
    agentId: "prospector",
    categories: ["Research"],
    integrations: [
      INTEGRATIONS.x,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
      INTEGRATIONS.linkedin,
      INTEGRATIONS.youtube,
      INTEGRATIONS.facebook,
    ],
    goal: "Secure a recognizable social identity without forcing the brand into a weak platform-specific variation.",
    inputs: [
      "The brand name, website, positioning, and words the handle should avoid.",
      "Priority platforms and any existing accounts that must be preserved.",
      "The preferred balance between a short brand handle and a descriptive fallback.",
    ],
    workflow: [
      "Generate a small set of pronounceable handles that feel native to the brand, then reject generic suffixes and confusing spellings.",
      "Check the exact profile URL and platform search for every candidate on each priority network.",
      "Treat a missing profile only as an availability signal. Confirm availability in the platform signup flow before recommending a claim.",
      "Rank candidates by cross-platform consistency, memorability, pronunciation, and collision risk.",
      "Prepare the chosen display name, bio, website link, avatar, and recovery checklist for each platform.",
      "Hand account creation or an unavailable credential to the Setup agent, preserving the approved handle and profile details.",
    ],
    deliverables: [
      "A cross-platform availability matrix with evidence links and the time checked.",
      "One lead handle, two fallbacks, and a concise reason for the ranking.",
      "A platform-by-platform setup checklist with consistent profile copy.",
      "A clear approval step before any account is created or handle is claimed.",
    ],
    accessNotes: [
      "Public profile pages can indicate that a handle is unused, but only the platform signup flow can confirm it is claimable.",
      "Creating accounts may require the user's login, email or phone verification, CAPTCHA, or acceptance of platform terms.",
    ],
    guardrails: [
      ...sharedGuardrails,
      "Never create an account, accept terms, reserve a handle, or change an existing profile without explicit approval.",
      "Do not call a handle available solely because a public profile returns not found.",
    ],
  },
  {
    id: "founder-content",
    title: "Founder content",
    summary: "Draft useful posts from real customer signals.",
    task: "Turn recent customer questions, product changes, analytics, and market signals into concise founder-led posts in our voice. Save the strongest drafts for my review and avoid generic advice.",
    agentId: "content",
    categories: ["Content"],
    integrations: [
      INTEGRATIONS.analytics,
      INTEGRATIONS.x,
      INTEGRATIONS.linkedin,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
      INTEGRATIONS.youtube,
    ],
    goal: "Create founder-led content grounded in what the company is actually learning and building.",
    inputs: [
      "A saved founder or brand voice with examples of acceptable claims.",
      "Recent product changes, customer questions, or measured outcomes.",
      "The channels and audience segments the founder actually wants to reach.",
    ],
    workflow: [
      "Collect recent product changes, customer language, objections, and performance signals.",
      "Choose ideas with a useful point of view, proof, and a clear audience.",
      "Choose the right treatment for each channel: written insight, carousel outline, short-video script, or longer demonstration.",
      "Draft channel-native posts in the saved brand voice, including Instagram, TikTok, or YouTube only when the idea benefits from a visual treatment.",
      "Rank drafts by usefulness and likelihood of earning the right audience's attention.",
    ],
    deliverables: [
      "Two or three polished post drafts with hooks and intended channels.",
      "The source insight behind each draft and why it is timely.",
      "A recommended lead draft for review.",
    ],
    accessNotes: [
      "Analytics informs which ideas resonated; connected social accounts provide owned-content performance and audience responses.",
      "A destination channel is optional. The agent can still draft for review without publishing access.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "brand-content",
    title: "Brand content",
    summary: "Draft useful posts in the company voice.",
    task: "Turn recent product changes, customer proof, useful expertise, and measured outcomes into concise brand-led content. Save the strongest channel-native drafts for review without publishing them.",
    agentId: "content",
    categories: ["Content"],
    integrations: [
      INTEGRATIONS.analytics,
      INTEGRATIONS.x,
      INTEGRATIONS.linkedin,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
      INTEGRATIONS.youtube,
    ],
    goal: "Keep the brand account useful and current without relying on the founder's personal voice for every post.",
    inputs: [
      "A saved brand voice with approved claims and examples.",
      "Recent product changes, customer proof, questions, or measured outcomes.",
      "The channels, formats, and audience segments the brand account serves.",
    ],
    workflow: [
      "Collect recent product changes, customer language, approved proof, and content performance signals.",
      "Choose ideas that teach something useful, demonstrate the product, answer a real question, or provide credible proof.",
      "Match each idea to a channel-native format such as a short post, carousel outline, demonstration script, or customer story.",
      "Draft in the saved company voice and keep the brand account distinct from founder-led commentary.",
      "Rank drafts by usefulness, evidence quality, and fit for the intended audience.",
    ],
    deliverables: [
      "Two or three polished brand-account drafts with intended channels and formats.",
      "The evidence or source insight behind each draft.",
      "A recommended lead draft for review.",
    ],
    accessNotes: [
      "Analytics can inform which ideas and formats resonated; connected social accounts provide owned-content performance and audience responses.",
      "A destination channel is optional. The agent can prepare drafts for review without publishing access.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "conversion-review",
    title: "Conversion review",
    summary: "Find the biggest leak in the current funnel.",
    task: "Review our connected acquisition and conversion data, identify the single clearest funnel leak, explain the evidence, and propose one specific experiment with a measurable success condition.",
    agentId: "analyst",
    categories: ["Conversion"],
    integrations: [INTEGRATIONS.analytics, INTEGRATIONS.posthog],
    goal: "Identify the highest-leverage measurable obstacle between attention and conversion.",
    inputs: [
      "Named funnel stages with event or page definitions.",
      "A meaningful date range and enough volume to compare.",
      "The primary conversion and any known tracking changes.",
    ],
    workflow: [
      "Map the observable funnel stages and verify the available event definitions.",
      "Compare stage conversion rates by period and useful segment.",
      "Locate the largest credible leak and rule out tracking problems.",
      "Design the smallest experiment that can test the proposed explanation.",
    ],
    deliverables: [
      "A funnel table or chart.",
      "One prioritized leak with evidence and business impact.",
      "One experiment with owner, change, metric, and success threshold.",
    ],
    accessNotes: [
      "Google Analytics can establish acquisition and page-level movement; PostHog can validate product-event progression.",
      "If event coverage or sample size is insufficient, the output should be a tracking diagnosis rather than a conversion recommendation.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "community-opportunities",
    title: "Community opportunities",
    summary: "Relevant Reddit, Hacker News, and forum threads.",
    task: "Monitor the communities where our ideal customers spend time. Find high-intent questions we can genuinely help with, save the best opportunities, and draft value-first replies that respect each community's norms.",
    agentId: "prospector",
    categories: ["Find customers"],
    integrations: [
      INTEGRATIONS.reddit,
      INTEGRATIONS.hackerNews,
      INTEGRATIONS.facebook,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
    ],
    goal: "Find active community discussions where useful participation can build trust or create a qualified conversation.",
    inputs: [
      "A list of communities, accounts, creators, or topics where buyers spend time.",
      "Community-specific promotion rules and disallowed behaviors.",
      "A clear definition of what the company can credibly help with.",
    ],
    workflow: [
      "Search recent discussions, connected account comments, and approved public surfaces for concrete questions, pain, comparisons, and requests for recommendations.",
      "Check thread recency, engagement, author fit, and community self-promotion rules.",
      "Keep only threads where the company can add specific value without forcing a pitch.",
      "Draft a useful reply that answers the question before mentioning the product, if mentioning it is appropriate at all.",
    ],
    deliverables: [
      "A prioritized table of threads with links, community, intent signal, and fit.",
      "A draft reply and participation note for every selected thread.",
      "A clear skip reason for tempting but inappropriate opportunities.",
    ],
    accessNotes: [
      "Facebook Groups and private communities are included only when the user has authorized access and platform rules allow it.",
      "Instagram and TikTok are strongest here for comments, mentions, and questions around connected professional or creator accounts, not unrestricted network-wide search.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "prospect-triggers",
    title: "Prospect triggers",
    summary: "Job changes, launches, and timely reasons to reach out.",
    task: "Find timely public triggers among ideal prospects, such as a launch, new role, hiring signal, product change, or stated pain. Save qualified matches with the evidence and a direct, relevant outreach angle.",
    agentId: "prospector",
    categories: ["Find customers"],
    integrations: [
      INTEGRATIONS.linkedin,
      INTEGRATIONS.x,
      INTEGRATIONS.facebook,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
    ],
    goal: "Detect recent events that create a credible reason for a relevant sales conversation now.",
    inputs: [
      "A target-account or ideal-customer definition.",
      "The trigger types that materially change buying likelihood.",
      "A maximum trigger age and a clear exclusion list.",
    ],
    workflow: [
      "Review target accounts, company Pages, professional profiles, creator updates, and public posts for launches, hiring, role changes, new initiatives, and explicit pain.",
      "Verify that each trigger is recent and connected to a problem the product solves.",
      "Score account fit, trigger strength, and timing.",
      "Develop a direct outreach angle tied to the observed event.",
    ],
    deliverables: [
      "A qualified trigger table with company, person, source, date, and evidence.",
      "Fit and timing scores with a recommended next step.",
      "A concise outreach angle for review.",
    ],
    accessNotes: [
      "Use first-party company and creator posts as evidence, not inferred personal data.",
      "Facebook, Instagram, and TikTok coverage depends on connected or otherwise approved access and may be incomplete.",
    ],
    guardrails: sharedGuardrails,
  },
];
