import type { Playbook } from "./playbook-types";
import { INTEGRATIONS, sharedGuardrails } from "./playbook-catalog-foundations";

export const researchPlaybooks: Playbook[] = [
  {
    id: "content-repurpose",
    title: "Reuse what worked",
    summary: "Turn proven material into new channel-native drafts.",
    task: "Review our strongest recent content and customer conversations. Rework the best ideas into new channel-native drafts without repeating the original wording, and save them for review.",
    agentId: "content",
    categories: ["Content"],
    integrations: [
      INTEGRATIONS.x,
      INTEGRATIONS.linkedin,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
      INTEGRATIONS.youtube,
    ],
    goal: "Extend the useful life of proven ideas while making every new draft native to its destination.",
    inputs: [
      "Source material with an observable performance or customer-quality signal.",
      "The permitted destination channels and available production formats.",
      "Brand voice and any claims that require fresh verification.",
    ],
    workflow: [
      "Identify source material with strong engagement, conversion, or customer resonance.",
      "Extract the durable insight rather than copying the original wording.",
      "Choose formats and channels that suit the idea, such as an X thread, LinkedIn post, Instagram carousel, TikTok script, or YouTube outline.",
      "Draft fresh versions with the right length, hook, and call to action for each channel.",
    ],
    deliverables: [
      "A source-to-draft map explaining what was reused and why.",
      "Channel-native drafts ready for review.",
      "A recommended publishing order.",
    ],
    accessNotes: [
      "Connected channel analytics improve source selection, but the playbook can work from user-provided source material.",
      "Do not treat engagement across different networks as directly comparable without normalizing for reach and format.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "customer-questions",
    title: "Answer customer questions",
    summary: "Build content from the questions buyers keep asking.",
    task: "Collect recurring questions and objections from connected conversations, communities, search signals, and prospect notes. Draft clear answers that can become posts, help content, or sales material, and save the best drafts.",
    agentId: "content",
    categories: ["Content", "Research"],
    integrations: [
      INTEGRATIONS.gmail,
      INTEGRATIONS.hubspot,
      INTEGRATIONS.reddit,
      INTEGRATIONS.facebook,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
    ],
    goal: "Turn repeated buyer confusion and objections into reusable, evidence-backed answers.",
    inputs: [
      "Customer-facing conversations or notes with permission to analyze them.",
      "A product truth source for validating answers and claims.",
      "The intended output surfaces, such as help, sales, social, or website copy.",
    ],
    workflow: [
      "Collect recent questions and objections from customer-facing sources.",
      "Cluster duplicates while preserving the customer's original language.",
      "Prioritize by frequency, purchase impact, and answerability.",
      "Draft direct answers and recommend the best format for each one.",
    ],
    deliverables: [
      "A ranked question and objection catalogue with source evidence.",
      "Draft answers for the highest-value themes.",
      "Recommended uses across content, help, and sales enablement.",
    ],
    accessNotes: [
      "CRM and email provide direct customer evidence; social comments add public questions and objections where access permits.",
      "Remove personal information from the output and quote private conversations only when the user has explicitly allowed it.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "launch-cycle",
    title: "Keep the launch alive",
    summary:
      "Plan the next launch angle instead of treating launch as one day.",
    task: "Review recent product changes, previous launch material, and audience response. Build the next focused launch angle with a clear hook, proof, channel plan, and the drafts needed for my review.",
    agentId: "content",
    categories: ["Content"],
    integrations: [
      INTEGRATIONS.x,
      INTEGRATIONS.linkedin,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
      INTEGRATIONS.youtube,
      INTEGRATIONS.productHunt,
    ],
    goal: "Create a repeatable sequence of launch moments around real product value and audience response.",
    inputs: [
      "A shipped product change with verified availability and claims.",
      "The launch audience, desired action, and proof available today.",
      "Prior launch assets and response data when available.",
    ],
    workflow: [
      "Review shipped changes, customer outcomes, previous messaging, and response data.",
      "Choose one audience and one fresh value angle.",
      "Build proof, hook, and a channel sequence that assigns a distinct job to text, carousel, short video, demo, and launch-directory formats.",
      "Draft the core launch assets and follow-up posts.",
    ],
    deliverables: [
      "A focused launch brief with audience, promise, proof, and hook.",
      "A short channel sequence and publishing cadence.",
      "Draft launch assets for review.",
    ],
    accessNotes: [
      "Channel connections provide owned-performance context and may later support approved publishing, but are not required to produce drafts.",
      "Do not promise availability, integrations, or customer outcomes that have not been verified.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "seo-opportunities",
    title: "Search opportunities",
    summary: "Queries and pages with a realistic path to traffic.",
    task: "Find high-intent search opportunities relevant to our product and current authority. Prioritize realistic queries, identify the page or content needed, and save a concise brief for the strongest opportunity.",
    agentId: "chief",
    categories: ["Search"],
    integrations: [
      INTEGRATIONS.searchConsole,
      INTEGRATIONS.semrush,
      INTEGRATIONS.analytics,
    ],
    goal: "Find search demand the company can credibly satisfy and convert.",
    inputs: [
      "A verified website property and target market.",
      "Current product positioning and conversion goals.",
      "Search Console history or a credible third-party demand source.",
    ],
    workflow: [
      "Review current queries, landing pages, rankings, and relevant competitor coverage.",
      "Group opportunities by search intent and product relevance.",
      "Estimate difficulty using current authority and the quality of competing results.",
      "Prioritize one opportunity and define the page required to win it.",
    ],
    deliverables: [
      "A ranked opportunity table with intent, evidence, difficulty, and business fit.",
      "A content brief for the strongest opportunity.",
      "A measurement plan covering impressions, clicks, and conversion.",
    ],
    accessNotes: [
      "Search Console supplies first-party query and page evidence; Semrush can extend competitor and demand coverage; Analytics validates downstream behavior.",
      "If the site is new or data is sparse, frame output as a hypothesis backlog rather than forecasted traffic.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "comparison-pages",
    title: "Comparison pages",
    summary: "Capture buyers comparing options in your category.",
    task: "Research how buyers compare products in our category. Identify one useful comparison or alternative page we can support honestly, then produce an evidence-based brief covering intent, structure, proof, and differentiation.",
    agentId: "chief",
    categories: ["Search"],
    integrations: [
      INTEGRATIONS.searchConsole,
      INTEGRATIONS.semrush,
      INTEGRATIONS.reddit,
    ],
    goal: "Help evaluation-stage buyers understand genuine differences without producing thin or misleading competitor pages.",
    inputs: [
      "A named comparison set and the buyer segment making the decision.",
      "Verified product capabilities, pricing, and limitations.",
      "Evidence of comparison intent from search or customer discussions.",
    ],
    workflow: [
      "Find comparison and alternative queries used by relevant buyers.",
      "Review community discussions and current result pages for decision criteria.",
      "Identify an angle supported by verifiable product differences and customer needs.",
      "Build a fair page structure with proof and clear fit guidance.",
    ],
    deliverables: [
      "A chosen comparison opportunity and evidence for its intent.",
      "A detailed page brief with sections, claims, proof, and differentiation.",
      "A list of facts that must be verified before publication.",
    ],
    accessNotes: [
      "Search data establishes demand; community discussions reveal decision criteria but should not be treated as representative research by themselves.",
      "Competitor claims must be checked against current primary sources before publication.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "ai-search-visibility",
    title: "AI search visibility",
    summary: "Track whether assistants mention and understand the product.",
    task: "Check how our product and category appear across relevant AI search questions. Record where we are absent or misrepresented, identify the source content likely to improve the answer, and recommend one concrete update.",
    agentId: "chief",
    categories: ["Search"],
    integrations: [
      INTEGRATIONS.openai,
      INTEGRATIONS.perplexity,
      INTEGRATIONS.anthropic,
    ],
    goal: "Understand how major assistants describe the category and whether the product appears accurately in buyer-relevant answers.",
    inputs: [
      "A stable question set representing discovery, comparison, and buying intent.",
      "Current product facts and canonical source pages.",
      "Access to at least two assistant or answer-engine surfaces for comparison.",
    ],
    workflow: [
      "Define representative discovery, comparison, and problem-aware questions.",
      "Run the same question set across available assistants and record citations.",
      "Compare mentions, accuracy, positioning, and source coverage.",
      "Identify the smallest source-content improvement likely to change future answers.",
    ],
    deliverables: [
      "A question-by-assistant visibility table.",
      "Important omissions or inaccuracies with supporting answer evidence.",
      "One prioritized source-content update and the rationale for it.",
    ],
    accessNotes: [
      "Run equivalent prompts in fresh sessions where possible and record model, date, citations, and personalization state.",
      "Assistant answers are samples, not rankings. Do not claim market-wide visibility from a small prompt set.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "backlink-opportunities",
    title: "Backlink opportunities",
    summary: "Relevant sites with a credible reason to reference you.",
    task: "Find credible backlink opportunities in our niche where our product, data, or expertise would genuinely improve an existing resource. Save only relevant opportunities with the page, contact path, and a non-spammy pitch angle.",
    agentId: "prospector",
    categories: ["Search", "Find customers"],
    integrations: [
      INTEGRATIONS.searchConsole,
      INTEGRATIONS.semrush,
      INTEGRATIONS.gmail,
    ],
    goal: "Find editorially credible link opportunities based on genuine usefulness, not volume outreach.",
    inputs: [
      "A target topic, market, and acceptable site-quality threshold.",
      "An asset, dataset, product capability, or expert point of view worth citing.",
      "Existing links and referring-domain data when available.",
    ],
    workflow: [
      "Review pages already ranking or linking in the target topic area.",
      "Find outdated, incomplete, or relevant resources the company can improve.",
      "Verify site quality, topical fit, contact path, and a specific reason to reference the company.",
      "Draft a concise pitch angle tied to the recipient's existing page.",
    ],
    deliverables: [
      "A prioritized opportunity table with page, site, fit, contact path, and rationale.",
      "The asset or expertise needed to earn each link.",
      "A tailored pitch draft for review.",
    ],
    accessNotes: [
      "Search and backlink tools identify candidates; Gmail is only for finding prior relationships or preparing reviewed outreach.",
      "Never send bulk outreach, invent a relationship, or recommend a link placement without a genuine editorial reason.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "campaign-watch",
    title: "Campaign watch",
    summary: "Spot spend or performance changes before they compound.",
    task: "Review connected campaign and conversion performance, flag material changes or wasted spend, explain the evidence, and recommend the smallest safe adjustment. Do not change budgets or campaigns without approval.",
    agentId: "ads",
    categories: ["Conversion"],
    integrations: [
      INTEGRATIONS.googleAds,
      INTEGRATIONS.meta,
      INTEGRATIONS.linkedInAds,
      INTEGRATIONS.tiktokAds,
      INTEGRATIONS.analytics,
    ],
    goal: "Detect material paid-media problems and opportunities early enough to act safely.",
    inputs: [
      "Connected ad accounts with currency, timezone, and attribution settings confirmed.",
      "The primary conversion, target efficiency, and minimum decision volume.",
      "Recent change history so the agent can separate expected learning from faults.",
    ],
    workflow: [
      "Compare recent spend, delivery, conversion, and efficiency against the previous period and targets.",
      "Check whether changes are isolated to a campaign, audience, creative, placement, or tracking issue.",
      "Prioritize by financial impact and confidence.",
      "Recommend the smallest reversible adjustment and its monitoring window.",
    ],
    deliverables: [
      "A campaign performance table with material changes highlighted.",
      "A short explanation of the highest-impact issue or opportunity.",
      "A proposed adjustment, expected effect, and approval requirement.",
    ],
    accessNotes: [
      "Compare Google, Meta, LinkedIn, and TikTok only where accounts are connected and conversion definitions are compatible.",
      "Platform-reported conversions and Analytics may use different attribution. Reconcile the difference before recommending spend changes.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "competitor-watch",
    title: "Watch competitors",
    summary: "Product, positioning, pricing, and channel changes.",
    task: "Track meaningful competitor changes across product, positioning, pricing, content, and distribution. Ignore routine noise and report only changes that create a risk or opportunity for us, with one recommended response.",
    agentId: "chief",
    categories: ["Research"],
    integrations: [
      INTEGRATIONS.x,
      INTEGRATIONS.linkedin,
      INTEGRATIONS.facebook,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
      INTEGRATIONS.youtube,
      INTEGRATIONS.productHunt,
    ],
    goal: "Separate consequential competitive moves from routine activity and turn them into a useful response.",
    inputs: [
      "A maintained competitor and category-entrant list.",
      "The customer segments and buying criteria that matter to the company.",
      "A previous snapshot so the agent can distinguish changes from existing facts.",
    ],
    workflow: [
      "Monitor named competitors and category entrants across websites, product, pricing, positioning, hiring, launch directories, and available social or video channels.",
      "Verify each change against a primary source where possible.",
      "Assess which customer segment and buying criterion the move affects.",
      "Recommend whether to respond, learn, or ignore.",
    ],
    deliverables: [
      "A concise change log with source, date, and significance.",
      "The risk or opportunity created for the company.",
      "One recommended response for material changes only.",
    ],
    accessNotes: [
      "Social coverage varies by platform and account access. A missing post is not evidence that a competitor was inactive.",
      "Use primary pages, release notes, pricing pages, and direct posts before secondary commentary.",
    ],
    guardrails: sharedGuardrails,
  },
  {
    id: "customer-language",
    title: "Customer language",
    summary: "The phrases buyers use for problems and desired outcomes.",
    task: "Collect recent language used by customers and ideal prospects to describe their pain, alternatives, objections, and desired outcomes. Group repeated themes and recommend specific wording improvements for our marketing.",
    agentId: "chief",
    categories: ["Research"],
    integrations: [
      INTEGRATIONS.hubspot,
      INTEGRATIONS.gmail,
      INTEGRATIONS.reddit,
      INTEGRATIONS.x,
      INTEGRATIONS.facebook,
      INTEGRATIONS.instagram,
      INTEGRATIONS.tiktok,
    ],
    goal: "Build a current voice-of-customer reference from the words buyers actually use.",
    inputs: [
      "A defined customer segment and buying stage.",
      "Recent customer-facing material with permission to analyze it.",
      "The marketing surfaces whose language should improve.",
    ],
    workflow: [
      "Collect recent verbatim language from customer conversations and public discussions.",
      "Tag statements by pain, trigger, alternative, objection, desired outcome, and proof.",
      "Cluster repeated phrases without smoothing away meaningful distinctions.",
      "Map the strongest language to specific marketing surfaces.",
    ],
    deliverables: [
      "A theme table with representative language and source context.",
      "Repeated phrases and important differences by segment or stage.",
      "Specific copy recommendations for priority marketing surfaces.",
    ],
    accessNotes: [
      "CRM and email are the strongest direct-customer sources; public social material broadens the sample but may overrepresent vocal users.",
      "Label every quote by source type and context, remove personal data, and never fabricate verbatim language.",
    ],
    guardrails: sharedGuardrails,
  },
];
