import { Body, Head, Html, Preview } from "@react-email/components";

import type { WorkspaceInvitationMessageInput } from "../../workspace-invitation-message";
import { PREVIEW_EMAIL_LOGO_URL } from "../../branding";
import { createWorkspaceInvitationMessage } from "../../workspace-invitation-message";

export type WorkspaceInvitationEmailProps = WorkspaceInvitationMessageInput;

/**
 * Previews the invitation exactly as the relay sends it: the markup comes from
 * `createWorkspaceInvitationMessage`, which the relay renders without React.
 */
export function WorkspaceInvitationEmail(props: WorkspaceInvitationEmailProps) {
  const message = createWorkspaceInvitationMessage(props);
  return (
    <Html lang="en">
      <Head />
      <Preview>{message.preview}</Preview>
      <Body style={{ margin: 0, padding: 0, backgroundColor: "#0a0a0a" }}>
        {/* Generated by the builder above, which escapes every input. */}
        <div dangerouslySetInnerHTML={{ __html: message.content }} />
      </Body>
    </Html>
  );
}

WorkspaceInvitationEmail.PreviewProps = {
  invitationUrl: "https://heychief.sh/invitations/example",
  inviterEmail: "alex@example.com",
  inviterName: "Alex Rivera",
  inviterImage: null,
  logoUrl: PREVIEW_EMAIL_LOGO_URL,
  relayHost: "relay.heychief.sh",
  role: "member",
  workspaceName: "Acme",
} satisfies WorkspaceInvitationEmailProps;

export default WorkspaceInvitationEmail;
