import { writeFileSync } from "node:fs";
import { join } from "node:path";

import type { EveWorkspaceInput } from "./eve-workspace.js";
import { composeWorkspaceInstructions, getAgent } from "./agents.js";
import { cloudSpecialistInstructions } from "./eve-workspace.js";

export const CONVEX_SPECIALISTS = [
  "brand",
  "prospector",
  "setup",
  "analyst",
  "ads",
  "content",
] as const;

function deployedRules(name: string, delegates: readonly string[]) {
  return `# Convex deployment

You run as ${name} in an isolated Convex project. Use Chief control-plane tools
for durable workspace reads and writes.${
    delegates.length > 0
      ? ` Delegate only bounded work to the subagents configured in this agent pack: ${delegates.join(
          ", ",
        )}. You own verification and the final user-facing answer.`
      : " This agent pack has no subagents, so complete work directly."
  } Never expose credentials or claim a tool succeeded unless its response confirms success.`;
}

export function materializeConvexWorkspace(
  root: string,
  input: EveWorkspaceInput,
) {
  const rootAgent = getAgent(input.agentId ?? "chief");
  if (!rootAgent) throw new Error("Deployment agent missing from roster.");
  const specialistIds = rootAgent.delegates ?? [];
  const activeCloudAutomations = (input.automations ?? []).filter(
    (automation) =>
      automation.status === "active" && automation.placement === "cloud",
  );
  if (activeCloudAutomations.length) {
    throw new Error(
      `Cloud schedules are not supported by the minimal Convex runtime: ${activeCloudAutomations.map(({ id }) => id).join(", ")}.`,
    );
  }

  const playbooks = (input.playbooks ?? [])
    .map(({ title, summary }) => `- ${title}: ${summary.trim().slice(0, 500)}`)
    .join("\n");
  const system = composeWorkspaceInstructions(
    [
      rootAgent.instructions,
      deployedRules(rootAgent.name, specialistIds),
      playbooks ? `# Available playbooks\n\n${playbooks}` : undefined,
    ]
      .filter(Boolean)
      .join("\n\n"),
    input.context,
  );
  const specialists = Object.fromEntries(
    specialistIds.map((id) => {
      const agent = getAgent(id);
      if (!agent) throw new Error(`Persona missing from roster: ${id}`);
      return [
        id,
        [
          cloudSpecialistInstructions(agent),
          `Complete only the bounded task supplied by ${rootAgent.name}. Do not delegate, publish, spend, message people, or request credentials. Return concise evidence, uncertainty, and a draft or recommendation for ${rootAgent.name} to verify.`,
          input.context?.trim()
            ? `Workspace context:\n${input.context.trim()}`
            : undefined,
        ]
          .filter(Boolean)
          .join("\n\n"),
      ];
    }),
  );

  writeFileSync(
    join(root, "convex", "generated.ts"),
    [
      "// Generated by Chief. Do not edit in a deployed workspace.",
      `export const SYSTEM_INSTRUCTIONS = ${JSON.stringify(system)};`,
      `export const SPECIALIST_INSTRUCTIONS = ${JSON.stringify(specialists, null, 2)} as const;`,
      "",
    ].join("\n"),
  );
  return {
    playbookCount: input.playbooks?.length ?? 0,
    specialistIds: [...specialistIds],
  };
}
