import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { AgentDefinition } from "./types.js";
import {
  composeWorkspaceInstructions,
  defaultAgents,
  getAgent,
} from "./agents.js";

const GENERATED =
  "<!-- GENERATED by Chief from the canonical filesystem agent definition. -->";
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const LOCAL_ONLY_SPECIALIST_TOOLS =
  /brandProfileSave|contentSave|uiPresentChart|prospectsSave|campaignsSave|localTools|tools\.chief/;

const SPECIALIST_RULES = `# Specialist contract

You are a private, inspect-only specialist working for the calling agent. The
user never messages you through this run. Answer only the bounded task the
caller delegates and return evidence, analysis, or a draft for it to verify and
synthesize.

- Treat the delegation message and Workspace section as your complete context.
- You do not have Executor or durable product-write access. Do not save records,
  schedule work, publish, spend, message people, or request credentials.
- Inspect supplied files with read-only file tools and public sources with
  read-only web tools. Do not run shell commands or write files.
- State evidence and uncertainty plainly. Return the result to the caller, not the user.`;

const DEPLOYED_CHIEF_RULES = `# Deployed orchestration

You are running in Eve with the private subagents declared in this deployment.
Use Eve's subagent tool for bounded Brand Researcher, Content Writer, Analyst,
Prospector, Ads Manager, and Setup work. Do not call localTools.specialistsDelegate;
that tool exists only in the desktop-local runtime. Chief still owns the final
user-facing synthesis.`;

interface EveAutomationGrant {
  version: 1;
  approvedAt: number;
  toolPatterns: string[];
}

export interface EveAutomationExport {
  id: string;
  agentId: string;
  cron: string;
  timezone: string;
  instructions: string;
  grant?: EveAutomationGrant;
  placement: "local" | "cloud";
  onceAt?: number;
  status: "draft" | "active" | "paused" | "needs_approval" | "error";
}

export interface EvePlaybookExport {
  id: string;
  title: string;
  summary: string;
  instructions: string;
}

export interface EveWorkspaceInput {
  automations?: EveAutomationExport[];
  context?: string;
  playbooks?: EvePlaybookExport[];
  hostedExecutor?: boolean;
  controlPlane?: boolean;
  channels?: { kind: "slack" }[];
}

export function cloudSpecialistInstructions(agent: AgentDefinition) {
  const lines = (agent.baseInstructions ?? agent.instructions).split("\n");
  const blocks: { bullet: boolean; lines: string[] }[] = [];
  for (const line of lines) {
    if (line.startsWith("- ")) {
      blocks.push({ bullet: true, lines: [line] });
    } else if (blocks.at(-1)?.bullet && line.startsWith("#")) {
      blocks.push({ bullet: false, lines: [line] });
    } else {
      const block = blocks.at(-1);
      if (block) block.lines.push(line);
      else blocks.push({ bullet: false, lines: [line] });
    }
  }
  return blocks
    .filter(
      (block) =>
        !block.bullet ||
        !LOCAL_ONLY_SPECIALIST_TOOLS.test(block.lines.join("\n")),
    )
    .flatMap((block) => block.lines)
    .join("\n")
    .replaceAll(/\n{3,}/g, "\n\n")
    .trim();
}

function assertSlug(value: string, kind: string) {
  if (!SLUG.test(value)) {
    throw new Error(`Invalid ${kind} id: ${value}`);
  }
}

function composeSpecialistInstructions(
  id: string,
  instructions: string,
  context?: string,
) {
  const workspaceContext = context?.trim();
  return [
    instructions,
    id === "setup"
      ? `${SPECIALIST_RULES}\n\nThe Setup task is the exception to the inspect-only tool rule: use the configured Executor connection to inspect and establish selected integrations. Never claim a connection succeeded without a real verification call. Return unavoidable credential or consent requirements to Chief.`
      : SPECIALIST_RULES,
    workspaceContext ? `# Workspace\n\n${workspaceContext}` : undefined,
  ]
    .filter(Boolean)
    .join("\n\n");
}

function writeAgentModule(
  path: string,
  description: string,
  limits: { input: number; output: number },
) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief from the canonical filesystem agent definition.",
      'import { defineAgent } from "eve";',
      'import { experimental_chatgpt } from "eve/models/openai";',
      "",
      "export default defineAgent({",
      `  description: ${JSON.stringify(description)},`,
      "  model:",
      '    process.env.VERCEL || process.env.NODE_ENV === "production"',
      '      ? process.env.CHIEF_DEPLOYMENT_MODEL ?? "xai/grok-4.3"',
      "      : experimental_chatgpt(),",
      "  modelContextWindowTokens: 200_000,",
      "  limits: {",
      `    maxInputTokensPerSession: ${limits.input.toLocaleString("en-US").replaceAll(",", "_")},`,
      `    maxOutputTokensPerSession: ${limits.output.toLocaleString("en-US").replaceAll(",", "_")},`,
      "  },",
      "});",
      "",
    ].join("\n"),
  );
}

function writeSandboxModule(path: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief from the canonical filesystem agent definition.",
      'import { defaultBackend, defineSandbox } from "eve/sandbox";',
      "",
      "export default defineSandbox({",
      "  backend: defaultBackend({",
      '    microsandbox: { networkPolicy: "deny-all" },',
      '    vercel: { networkPolicy: "deny-all" },',
      "  }),",
      "});",
      "",
    ].join("\n"),
  );
}

function writeEveChannel(path: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief. Route credentials are injected at deployment time.",
      'import { eveChannel } from "eve/channels/eve";',
      'import { httpBasic, localDev, placeholderAuth, vercelOidc } from "eve/channels/auth";',
      "",
      "const password = process.env.CHIEF_EVE_ROUTE_PASSWORD;",
      "const desktopAuth = password",
      '  ? httpBasic({ username: "chief-desktop", password })',
      "  : placeholderAuth();",
      "",
      "export default eveChannel({",
      "  auth: [",
      "    vercelOidc(),",
      "    desktopAuth,",
      "    localDev(),",
      "  ],",
      "});",
      "",
    ].join("\n"),
  );
}

function writeSlackChannel(path: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief. Slack credentials are injected at deployment time.",
      'import { slackChannel } from "eve/channels/slack";',
      "",
      "export default slackChannel({});",
      "",
    ].join("\n"),
  );
}

function writeDisabledTool(path: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief from the canonical filesystem agent definition.",
      'import { disableTool } from "eve/tools";',
      "",
      "export default disableTool();",
      "",
    ].join("\n"),
  );
}

function writeExecutorConnection(path: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief. This connection runs in Eve's trusted host process.",
      'import { defineMcpClientConnection } from "eve/connections";',
      "",
      "const configuredUrl = process.env.EXECUTOR_MCP_URL;",
      'const url = configuredUrl ?? "https://executor.invalid/mcp";',
      "",
      "export default defineMcpClientConnection({",
      "  url,",
      '  description: "Connected marketing integrations and durable Chief workspace tools.",',
      "  auth: {",
      "    getToken: async () => {",
      '      if (!configuredUrl) throw new Error("EXECUTOR_MCP_URL is required to call Executor.");',
      "      const token = process.env.EXECUTOR_MCP_TOKEN;",
      '      if (!token) throw new Error("EXECUTOR_MCP_TOKEN is required to call Executor.");',
      "      return { token };",
      "    },",
      "  },",
      "});",
      "",
    ].join("\n"),
  );
}

function writeControlPlaneConnection(path: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief. The workspace capability is injected by the deployment host.",
      'import { defineOpenAPIConnection } from "eve/connections";',
      "",
      "const configuredBase = process.env.CHIEF_CONTROL_PLANE_API_BASE_URL;",
      'const base = configuredBase ?? "https://control-plane.invalid";',
      "const token = process.env.CHIEF_CONTROL_PLANE_TOKEN;",
      "",
      "export default defineOpenAPIConnection({",
      "  spec: `${base}/agent-tools/openapi.json`,",
      "  baseUrl: base,",
      '  description: "Durable Chief workspace records and connected control-plane sources.",',
      "  auth: {",
      "    getToken: async () => {",
      '      if (!configuredBase || !token) throw new Error("Chief control-plane credentials are required.");',
      "      return { token };",
      "    },",
      "  },",
      "});",
      "",
    ].join("\n"),
  );
}

export function materializeEveWorkspace(
  root: string,
  input: EveWorkspaceInput,
) {
  const agentRoot = join(root, "agent");
  const chief = getAgent("cmo");
  if (!chief) throw new Error("Chief persona missing from roster.");
  const playbooks = input.playbooks ?? [];
  const automations = input.automations ?? [];
  const activeCloudAutomations = automations.filter(
    (automation) =>
      automation.status === "active" && automation.placement === "cloud",
  );
  if (activeCloudAutomations.length > 0) {
    throw new Error(
      `Cloud schedules cannot be deployed until Executor supports schedule-scoped capabilities. Move these schedules to local or pause them: ${activeCloudAutomations.map((automation) => automation.id).join(", ")}.`,
    );
  }

  mkdirSync(agentRoot, { recursive: true });
  writeFileSync(
    join(agentRoot, "instructions.md"),
    `${GENERATED}\n\n${composeWorkspaceInstructions(`${chief.instructions}\n\n${DEPLOYED_CHIEF_RULES}`, input.context)}\n`,
  );
  writeAgentModule(join(agentRoot, "agent.ts"), chief.description, {
    input: 500_000,
    output: 32_000,
  });
  writeSandboxModule(join(agentRoot, "sandbox.ts"));

  rmSync(join(agentRoot, "channels"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "channels"), { recursive: true });
  writeEveChannel(join(agentRoot, "channels", "eve.ts"));
  if (input.channels?.length) {
    writeSlackChannel(join(agentRoot, "channels", "slack.ts"));
  }

  rmSync(join(agentRoot, "connections"), { recursive: true, force: true });
  if (input.hostedExecutor || input.controlPlane) {
    mkdirSync(join(agentRoot, "connections"), { recursive: true });
  }
  if (input.hostedExecutor) {
    writeExecutorConnection(join(agentRoot, "connections", "executor.ts"));
  }
  if (input.controlPlane) {
    writeControlPlaneConnection(join(agentRoot, "connections", "chief.ts"));
  }

  rmSync(join(agentRoot, "tools"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "tools"), { recursive: true });

  rmSync(join(agentRoot, "subagents"), { recursive: true, force: true });
  for (const id of chief.delegates ?? []) {
    const agent = getAgent(id);
    if (!agent) throw new Error(`Persona missing from roster: ${id}`);
    const target = join(agentRoot, "subagents", id);
    mkdirSync(target, { recursive: true });
    writeFileSync(
      join(target, "instructions.md"),
      `${GENERATED}\n\n${composeSpecialistInstructions(
        id,
        cloudSpecialistInstructions(agent),
        input.context,
      )}\n`,
    );
    writeAgentModule(
      join(target, "agent.ts"),
      `Private inspect-only specialist. ${agent.description}`,
      { input: 100_000, output: 8_000 },
    );
    writeSandboxModule(join(target, "sandbox.ts"));
    if (id === "setup" && input.hostedExecutor) {
      mkdirSync(join(target, "connections"), { recursive: true });
      writeExecutorConnection(join(target, "connections", "executor.ts"));
    }
    if (
      input.controlPlane &&
      (id === "setup" || id === "prospector" || id === "brand")
    ) {
      mkdirSync(join(target, "connections"), { recursive: true });
      writeControlPlaneConnection(join(target, "connections", "chief.ts"));
    }
    mkdirSync(join(target, "tools"), { recursive: true });
    writeDisabledTool(join(target, "tools", "bash.ts"));
    writeDisabledTool(join(target, "tools", "write_file.ts"));
  }

  rmSync(join(agentRoot, "skills"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "skills"), { recursive: true });
  for (const playbook of playbooks) {
    assertSlug(playbook.id, "playbook");
    writeFileSync(
      join(agentRoot, "skills", `${playbook.id}.md`),
      [
        "---",
        `name: ${playbook.id}`,
        `description: ${JSON.stringify(playbook.summary)}`,
        "---",
        "",
        playbook.instructions,
        "",
      ].join("\n"),
    );
  }

  rmSync(join(agentRoot, "lib"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "lib"), { recursive: true });
  const roster = defaultAgents.map(({ id, name, role, description }) => ({
    id,
    name,
    role,
    description,
  }));
  writeFileSync(
    join(agentRoot, "lib", "roster.ts"),
    `export const roster = ${JSON.stringify(roster, null, 2)} as const;\n`,
  );

  rmSync(join(agentRoot, "schedules"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "schedules"), { recursive: true });

  return {
    agent: chief,
    automationCount: 0,
    playbookCount: playbooks.length,
    specialistIds: [...(chief.delegates ?? [])],
  };
}

export function readEveWorkspaceInput(root: string): EveWorkspaceInput {
  const inputRoot = join(root, "workspace-input");
  const optional = (name: string) => {
    try {
      return readFileSync(join(inputRoot, name), "utf8");
    } catch {
      return undefined;
    }
  };
  const automations = JSON.parse(
    optional("automations.json") ?? "[]",
  ) as EveAutomationExport[];
  const playbooks = JSON.parse(
    optional("playbooks.json") ?? "[]",
  ) as EvePlaybookExport[];
  return {
    automations,
    context: optional("context.md"),
    playbooks,
  };
}
