import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  composeWorkspaceInstructions,
  defaultAgents,
  getAgent,
} from "./agents.js";

const SPECIALISTS = ["brand", "content", "analyst", "prospector", "ads"];
const GENERATED =
  "<!-- GENERATED by Chief from the canonical filesystem agent definition. -->";
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

const SPECIALIST_RULES = `# Specialist contract

You are a private, inspect-only specialist working for Chief. The user never
messages you directly. Answer only the bounded task Chief delegates to you and
return evidence, analysis, or a draft for Chief to verify and synthesize.

- Treat the delegation message and Workspace section as your complete context.
- You do not have Executor or durable product-write access. Do not save records,
  schedule work, publish, spend, message people, or request credentials.
- Inspect supplied files with read-only file tools and public sources with
  read-only web tools. Do not run shell commands or write files.
- State evidence and uncertainty plainly. Return the result to Chief, not the user.`;

interface EveAutomationGrant {
  version: 1;
  approvedAt: number;
  toolPatterns: string[];
}

export interface EveAutomationExport {
  id: string;
  agentId: string;
  cron: string;
  timezone: string;
  instructions: string;
  grant?: EveAutomationGrant;
  placement: "local" | "cloud";
  runOnceAt?: number;
  status: "draft" | "active" | "paused" | "needs_approval" | "error";
}

export interface EvePlaybookExport {
  id: string;
  title: string;
  summary: string;
  instructions: string;
}

export interface EveWorkspaceInput {
  automations?: EveAutomationExport[];
  context?: string;
  playbooks?: EvePlaybookExport[];
}

function assertSlug(value: string, kind: string) {
  if (!SLUG.test(value)) {
    throw new Error(`Invalid ${kind} id: ${value}`);
  }
}

function composeSpecialistInstructions(
  role: string,
  description: string,
  context?: string,
) {
  const workspaceContext = context?.trim();
  return [
    `# Identity\n\nYou are Chief's ${role.toLowerCase()} specialist. ${description}`,
    SPECIALIST_RULES,
    workspaceContext ? `# Workspace\n\n${workspaceContext}` : undefined,
  ]
    .filter(Boolean)
    .join("\n\n");
}

function writeAgentModule(path: string, description: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief from the canonical filesystem agent definition.",
      'import { defineAgent } from "eve";',
      'import { experimental_chatgpt } from "eve/models/openai";',
      "",
      "export default defineAgent({",
      `  description: ${JSON.stringify(description)},`,
      "  model: experimental_chatgpt(),",
      "  modelContextWindowTokens: 200_000,",
      "});",
      "",
    ].join("\n"),
  );
}

function writeSandboxModule(path: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief from the canonical filesystem agent definition.",
      'import { defineSandbox } from "eve/sandbox";',
      'import { microsandbox } from "eve/sandbox/microsandbox";',
      "",
      "export default defineSandbox({",
      '  backend: microsandbox({ networkPolicy: "deny-all" }),',
      "});",
      "",
    ].join("\n"),
  );
}

function writeDisabledTool(path: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief from the canonical filesystem agent definition.",
      'import { disableTool } from "eve/tools";',
      "",
      "export default disableTool();",
      "",
    ].join("\n"),
  );
}

function writeExecutorConnection(path: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief. This connection runs in Eve's trusted host process.",
      'import { defineMcpClientConnection } from "eve/connections";',
      "",
      "const configuredUrl = process.env.EXECUTOR_MCP_URL;",
      'const url = configuredUrl ?? "https://executor.invalid/mcp";',
      "",
      "export default defineMcpClientConnection({",
      "  url,",
      '  description: "Connected marketing integrations and durable Chief workspace tools.",',
      "  auth: {",
      "    getToken: async () => {",
      '      if (!configuredUrl) throw new Error("EXECUTOR_MCP_URL is required to call Executor.");',
      "      const token = process.env.EXECUTOR_MCP_TOKEN;",
      '      if (!token) throw new Error("EXECUTOR_MCP_TOKEN is required to call Executor.");',
      "      return { token };",
      "    },",
      "  },",
      "});",
      "",
    ].join("\n"),
  );
}

export function materializeEveWorkspace(
  root: string,
  input: EveWorkspaceInput,
) {
  const agentRoot = join(root, "agent");
  const chief = getAgent("cmo");
  if (!chief) throw new Error("Chief persona missing from roster.");
  const playbooks = input.playbooks ?? [];
  const automations = input.automations ?? [];
  const activeCloudAutomations = automations.filter(
    (automation) =>
      automation.status === "active" && automation.placement === "cloud",
  );
  if (activeCloudAutomations.length > 0) {
    throw new Error(
      `Cloud schedules cannot be deployed until Executor supports schedule-scoped capabilities. Move these schedules to local or pause them: ${activeCloudAutomations.map((automation) => automation.id).join(", ")}.`,
    );
  }

  mkdirSync(agentRoot, { recursive: true });
  writeFileSync(
    join(agentRoot, "instructions.md"),
    `${GENERATED}\n\n${composeWorkspaceInstructions(chief.instructions, input.context)}\n`,
  );
  writeAgentModule(join(agentRoot, "agent.ts"), chief.description);
  writeSandboxModule(join(agentRoot, "sandbox.ts"));

  rmSync(join(agentRoot, "connections"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "connections"), { recursive: true });
  writeExecutorConnection(join(agentRoot, "connections", "executor.ts"));

  rmSync(join(agentRoot, "tools"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "tools"), { recursive: true });
  writeDisabledTool(join(agentRoot, "tools", "agent.ts"));

  rmSync(join(agentRoot, "subagents"), { recursive: true, force: true });
  for (const id of SPECIALISTS) {
    const agent = getAgent(id);
    if (!agent) throw new Error(`Persona missing from roster: ${id}`);
    const target = join(agentRoot, "subagents", id);
    mkdirSync(target, { recursive: true });
    writeFileSync(
      join(target, "instructions.md"),
      `${GENERATED}\n\n${composeSpecialistInstructions(
        agent.role,
        agent.description,
        input.context,
      )}\n`,
    );
    writeAgentModule(
      join(target, "agent.ts"),
      `Private inspect-only specialist. ${agent.description}`,
    );
    writeSandboxModule(join(target, "sandbox.ts"));
    mkdirSync(join(target, "tools"), { recursive: true });
    writeDisabledTool(join(target, "tools", "bash.ts"));
    writeDisabledTool(join(target, "tools", "write_file.ts"));
  }

  rmSync(join(agentRoot, "skills"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "skills"), { recursive: true });
  for (const playbook of playbooks) {
    assertSlug(playbook.id, "playbook");
    writeFileSync(
      join(agentRoot, "skills", `${playbook.id}.md`),
      [
        "---",
        `name: ${playbook.id}`,
        `description: ${JSON.stringify(playbook.summary)}`,
        "---",
        "",
        playbook.instructions,
        "",
      ].join("\n"),
    );
  }

  rmSync(join(agentRoot, "lib"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "lib"), { recursive: true });
  const roster = defaultAgents
    .filter((agent) => agent.id !== "setup")
    .map(({ id, name, role, description }) => ({
      id,
      name,
      role,
      description,
    }));
  writeFileSync(
    join(agentRoot, "lib", "roster.ts"),
    `export const roster = ${JSON.stringify(roster, null, 2)} as const;\n`,
  );

  rmSync(join(agentRoot, "schedules"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "schedules"), { recursive: true });

  return {
    agent: chief,
    automationCount: 0,
    playbookCount: playbooks.length,
    specialistIds: [...SPECIALISTS],
  };
}

export function readEveWorkspaceInput(root: string): EveWorkspaceInput {
  const inputRoot = join(root, "workspace-input");
  const optional = (name: string) => {
    try {
      return readFileSync(join(inputRoot, name), "utf8");
    } catch {
      return undefined;
    }
  };
  const automations = JSON.parse(
    optional("automations.json") ?? "[]",
  ) as EveAutomationExport[];
  const playbooks = JSON.parse(
    optional("playbooks.json") ?? "[]",
  ) as EvePlaybookExport[];
  return {
    automations,
    context: optional("context.md"),
    playbooks,
  };
}
