import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  composeWorkspaceInstructions,
  defaultAgents,
  getAgent,
} from "./agents.js";

const SPECIALISTS = ["brand", "content", "analyst", "prospector", "ads"];
const GENERATED =
  "<!-- GENERATED by Chief from the canonical filesystem agent definition. -->";

export interface EveAutomationExport {
  id: string;
  agentId: string;
  cron: string;
  timezone: string;
  instructions: string;
  toolPatterns: string[];
  placement: "local" | "cloud";
}

export interface EvePlaybookExport {
  id: string;
  title: string;
  summary: string;
  instructions: string;
}

export interface EveWorkspaceInput {
  agentId?: string;
  automations?: EveAutomationExport[];
  context?: string;
  playbooks?: EvePlaybookExport[];
}

function writeAgentModule(path: string, description: string) {
  writeFileSync(
    path,
    [
      "// GENERATED by Chief from the canonical filesystem agent definition.",
      'import { defineAgent } from "eve";',
      "",
      "export default defineAgent({",
      `  description: ${JSON.stringify(description)},`,
      '  model: process.env.WORKSPACE_MODEL ?? "anthropic/claude-sonnet-4.6",',
      "});",
      "",
    ].join("\n"),
  );
}

export function materializeEveWorkspace(
  root: string,
  input: EveWorkspaceInput,
) {
  const agentRoot = join(root, "agent");
  const selectedAgent = getAgent(input.agentId ?? "cmo");
  if (!selectedAgent) {
    throw new Error(`Unknown deployment agent: ${input.agentId}`);
  }
  const singleAgent = Boolean(input.agentId);
  const playbooks = input.playbooks ?? [];
  const automations = input.automations ?? [];

  mkdirSync(agentRoot, { recursive: true });
  writeFileSync(
    join(agentRoot, "instructions.md"),
    `${GENERATED}\n\n${composeWorkspaceInstructions(selectedAgent.instructions, input.context)}\n`,
  );
  writeAgentModule(join(agentRoot, "agent.ts"), selectedAgent.description);

  rmSync(join(agentRoot, "subagents"), { recursive: true, force: true });
  for (const id of singleAgent ? [] : SPECIALISTS) {
    const agent = getAgent(id);
    if (!agent) throw new Error(`Persona missing from roster: ${id}`);
    const target = join(agentRoot, "subagents", id);
    mkdirSync(target, { recursive: true });
    writeFileSync(
      join(target, "instructions.md"),
      `${GENERATED}\n\n${agent.instructions}\n`,
    );
    writeAgentModule(join(target, "agent.ts"), agent.description);
  }

  rmSync(join(agentRoot, "skills"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "skills"), { recursive: true });
  for (const playbook of playbooks) {
    writeFileSync(
      join(agentRoot, "skills", `${playbook.id}.md`),
      [
        "---",
        `name: ${playbook.id}`,
        `description: ${JSON.stringify(playbook.summary)}`,
        "---",
        "",
        playbook.instructions,
        "",
      ].join("\n"),
    );
  }

  rmSync(join(agentRoot, "lib"), { recursive: true, force: true });
  if (!singleAgent) {
    mkdirSync(join(agentRoot, "lib"), { recursive: true });
    const roster = defaultAgents
      .filter((agent) => agent.id !== "setup")
      .map(({ id, name, role, description }) => ({
        id,
        name,
        role,
        description,
      }));
    writeFileSync(
      join(agentRoot, "lib", "roster.ts"),
      `export const roster = ${JSON.stringify(roster, null, 2)} as const;\n`,
    );
  }

  rmSync(join(agentRoot, "schedules"), { recursive: true, force: true });
  mkdirSync(join(agentRoot, "schedules"), { recursive: true });
  const cloudAutomations = automations.filter(
    (automation) =>
      automation.placement === "cloud" &&
      (!singleAgent || automation.agentId === selectedAgent.id),
  );
  for (const automation of cloudAutomations) {
    const body = [
      "---",
      `cron: "${automation.cron}"`,
      "---",
      `This is approved unattended work (${automation.id}).`,
      `You may call only these Executor tools: ${
        automation.toolPatterns.join(", ") || "read-only tools"
      }.`,
      "If the task needs any other mutation, record the required approval and stop.",
      "",
      automation.instructions,
      "",
    ].join("\n");
    writeFileSync(join(agentRoot, "schedules", `${automation.id}.md`), body);
  }

  return {
    agent: selectedAgent,
    automationCount: cloudAutomations.length,
    playbookCount: playbooks.length,
  };
}

export function readEveWorkspaceInput(root: string): EveWorkspaceInput {
  const inputRoot = join(root, "workspace-input");
  const optional = (name: string) => {
    try {
      return readFileSync(join(inputRoot, name), "utf8");
    } catch {
      return undefined;
    }
  };
  const deployment = JSON.parse(optional("deployment.json") ?? "{}") as {
    agentId?: string;
  };
  const automations = JSON.parse(
    optional("automations.json") ?? "[]",
  ) as EveAutomationExport[];
  const playbooks = JSON.parse(
    optional("playbooks.json") ?? "[]",
  ) as EvePlaybookExport[];
  return {
    agentId: deployment.agentId,
    automations,
    context: optional("context.md"),
    playbooks,
  };
}
