/**
 * Compiles the shared agent personas plus this workspace's inputs into eve's
 * filesystem layout. Inputs live in workspace-input/ (written by the desktop
 * app or the deploy agent):
 *   context.md        — brand brief gathered at account setup
 *   automations.json  — approved recurring work placed in the cloud
 */
import {
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  composeWorkspaceInstructions,
  defaultAgents,
  getAgent,
} from "@marketer/agent-runtime/agents";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const input = (name: string) => join(root, "workspace-input", name);
const agentDir = (...parts: string[]) => join(root, "agent", ...parts);

const SPECIALISTS = ["content", "analyst", "prospector", "ads"] as const;

interface AutomationExport {
  id: string;
  agentId: string;
  cron: string;
  timezone: string;
  instructions: string;
  toolPatterns: string[];
  placement: "local" | "cloud";
}

function readOptional(path: string): string | undefined {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return undefined;
  }
}

const GENERATED =
  "<!-- GENERATED by scripts/generate.ts — edit personas in packages/agent-runtime/src/agents/ -->";

// 1. Root agent: the CMO persona, operating rules, and the brand context.
const context = readOptional(input("context.md"));
const cmo = getAgent("cmo");
if (!cmo) throw new Error("CMO persona missing from the shared roster.");
writeFileSync(
  agentDir("instructions.md"),
  `${GENERATED}\n\n${composeWorkspaceInstructions(cmo.instructions, context)}\n`,
);

// 2. Specialists as eve subagents (instructions + config module each).
for (const id of SPECIALISTS) {
  const agent = getAgent(id);
  if (!agent) throw new Error(`Persona missing from the shared roster: ${id}`);
  mkdirSync(agentDir("subagents", id), { recursive: true });
  writeFileSync(
    agentDir("subagents", id, "instructions.md"),
    `${GENERATED}\n\n${agent.instructions}\n`,
  );
  writeFileSync(
    agentDir("subagents", id, "agent.ts"),
    [
      `// GENERATED by scripts/generate.ts — edit personas in packages/agent-runtime/src/agents/`,
      `import { defineAgent } from "eve";`,
      ``,
      `export default defineAgent({`,
      `  description: ${JSON.stringify(agent.description)},`,
      `  model: process.env.WORKSPACE_MODEL ?? "anthropic/claude-sonnet-4.6",`,
      `});`,
      ``,
    ].join("\n"),
  );
}

// 3. Roster for in-character discovery surfaces (Slack help, MCP list_agents).
mkdirSync(agentDir("lib"), { recursive: true });
const roster = defaultAgents
  .filter((agent) => agent.id !== "setup")
  .map(({ id, name, role, description }) => ({ id, name, role, description }));
writeFileSync(
  agentDir("lib", "roster.ts"),
  [
    "// GENERATED by scripts/generate.ts",
    "export interface RosterEntry {",
    "  id: string;",
    "  name: string;",
    "  role: string;",
    "  description: string;",
    "}",
    "",
    `export const roster: RosterEntry[] = ${JSON.stringify(roster, null, 2)};`,
    "",
  ].join("\n"),
);

// 4. Cloud-placed automations become eve schedules (markdown task mode).
const automations: AutomationExport[] = JSON.parse(
  readOptional(input("automations.json")) ?? "[]",
);
rmSync(agentDir("schedules"), { recursive: true, force: true });
const cloudAutomations = automations.filter(
  (automation) => automation.placement === "cloud",
);
mkdirSync(agentDir("schedules"), { recursive: true });
for (const automation of cloudAutomations) {
  const body = [
    "---",
    `cron: "${automation.cron}"`,
    "---",
    `This is an approved unattended run (automation ${automation.id}).`,
    `You may call only these Executor tools: ${
      automation.toolPatterns.join(", ") || "read-only tools"
    }.`,
    "If the task needs any other mutation, stop and record what additional approval is required.",
    "",
    automation.instructions,
  ].join("\n");
  writeFileSync(agentDir("schedules", `${automation.id}.md`), `${body}\n`);
}

console.log(
  `generated: root instructions${context ? " (+context)" : ""}, ${SPECIALISTS.length} subagents, roster, ${cloudAutomations.length} cloud schedule(s)`,
);
