export const authSchemaContract = {
  account: {
    table: "account",
    fields: [
      "accessToken",
      "accessTokenExpiresAt",
      "accountId",
      "createdAt",
      "id",
      "idToken",
      "password",
      "providerId",
      "refreshToken",
      "refreshTokenExpiresAt",
      "scope",
      "updatedAt",
      "userId",
    ],
  },
  deviceCode: {
    table: "device_code",
    fields: [
      "clientId",
      "deviceCode",
      "expiresAt",
      "id",
      "lastPolledAt",
      "pollingInterval",
      "scope",
      "status",
      "userCode",
      "userId",
    ],
  },
  invitation: {
    table: "invitation",
    fields: [
      "createdAt",
      "email",
      "expiresAt",
      "id",
      "inviterId",
      "organizationId",
      "role",
      "status",
    ],
  },
  jwks: {
    table: "jwks",
    fields: ["createdAt", "expiresAt", "id", "privateKey", "publicKey"],
  },
  oauthAccessToken: {
    table: "oauth_access_token",
    fields: [
      "clientId",
      "createdAt",
      "expiresAt",
      "id",
      "referenceId",
      "refreshId",
      "scopes",
      "sessionId",
      "token",
      "userId",
    ],
  },
  oauthClient: {
    table: "oauth_client",
    fields: [
      "clientId",
      "clientSecret",
      "contacts",
      "createdAt",
      "disabled",
      "enableEndSession",
      "grantTypes",
      "icon",
      "id",
      "metadata",
      "name",
      "policy",
      "postLogoutRedirectUris",
      "public",
      "redirectUris",
      "referenceId",
      "requirePKCE",
      "responseTypes",
      "scopes",
      "skipConsent",
      "softwareId",
      "softwareStatement",
      "softwareVersion",
      "subjectType",
      "tokenEndpointAuthMethod",
      "tos",
      "type",
      "updatedAt",
      "uri",
      "userId",
    ],
  },
  oauthConsent: {
    table: "oauth_consent",
    fields: [
      "clientId",
      "createdAt",
      "id",
      "referenceId",
      "scopes",
      "updatedAt",
      "userId",
    ],
  },
  oauthRefreshToken: {
    table: "oauth_refresh_token",
    fields: [
      "authTime",
      "clientId",
      "createdAt",
      "expiresAt",
      "id",
      "referenceId",
      "revoked",
      "scopes",
      "sessionId",
      "token",
      "userId",
    ],
  },
  organization: {
    table: "organization",
    fields: ["createdAt", "id", "logo", "metadata", "name", "slug"],
  },
  member: {
    table: "member",
    fields: ["createdAt", "id", "organizationId", "role", "userId"],
  },
  session: {
    table: "session",
    fields: [
      "activeOrganizationId",
      "createdAt",
      "expiresAt",
      "id",
      "ipAddress",
      "token",
      "updatedAt",
      "userAgent",
      "userId",
    ],
  },
  user: {
    table: "user",
    fields: [
      "createdAt",
      "email",
      "emailVerified",
      "id",
      "image",
      "name",
      "updatedAt",
    ],
  },
  verification: {
    table: "verification",
    fields: [
      "createdAt",
      "expiresAt",
      "id",
      "identifier",
      "updatedAt",
      "value",
    ],
  },
} as const;

export type AuthSchemaModel = keyof typeof authSchemaContract;
