// GENERATED by Chief. Route credentials are injected at deployment time.
import {
  httpBasic,
  localDev,
  placeholderAuth,
  vercelOidc,
} from "eve/channels/auth";
import { eveChannel } from "eve/channels/eve";

const password = process.env.CHIEF_EVE_ROUTE_PASSWORD;
const desktopAuth = password
  ? httpBasic({ username: "chief-desktop", password })
  : placeholderAuth();

export default eveChannel({
  auth: [vercelOidc(), desktopAuth, localDev()],
});
