// GENERATED by Chief from the canonical filesystem agent definition.
import { defineAgent } from "eve";

export default defineAgent({
  description:
    "Top-level orchestrator. Owns strategy, delegates to specialist agents, answers anything about your marketing.",
  model: process.env.WORKSPACE_MODEL ?? "anthropic/claude-sonnet-4.6",
});
