// GENERATED by Chief from the canonical filesystem agent definition.
import { defineAgent } from "eve";
import { experimental_chatgpt } from "eve/models/openai";

export default defineAgent({
  description:
    "Top-level orchestrator. Owns strategy, delegates to specialist agents, answers anything about your marketing.",
  model: experimental_chatgpt(),
  modelContextWindowTokens: 200_000,
});
