// GENERATED by Chief from the canonical filesystem agent definition.
import { defineSandbox } from "eve/sandbox";
import { microsandbox } from "eve/sandbox/microsandbox";

export default defineSandbox({
  backend: microsandbox({ networkPolicy: "deny-all" }),
});
