import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * Cloud state for identity, billing, and shared integration connections.
 * Private agent configuration, conversations, prospects, trends, drafts,
 * and schedules live in the encrypted local libSQL database instead.
 *
 * There is no workspace table: a "workspace" IS the better-auth organization
 * (owned by the betterAuth component on this deployment). Rows carry
 * `organizationId` — the org id minted by better-auth and present in every
 * JWT payload — so data is scoped per company without duplicating the org
 * concept.
 */
export default defineSchema({
  /**
   * Social presence for a workspace. No OAuth: agents only draft and read
   * public pages, so a handle + canonical URL is all we store.
   */
  socialAccount: defineTable({
    organizationId: v.string(),
    platform: v.union(
      v.literal("x"),
      v.literal("instagram"),
      v.literal("linkedin"),
      v.literal("tiktok"),
      v.literal("youtube"),
      v.literal("reddit"),
    ),
    handle: v.string(),
    url: v.string(),
  })
    .index("by_organization", ["organizationId"])
    .index("by_organization_platform", ["organizationId", "platform"]),

  channel: defineTable({
    organizationId: v.string(),
    provider: v.string(), // "google-analytics" | "google-ads" | "x" | "reddit" | ...
    /** Product surface this connection powers: "analytics" | "ads" | "social" | ... */
    category: v.optional(v.string()),
    displayName: v.string(),
    status: v.union(
      v.literal("connected"),
      v.literal("disconnected"),
      v.literal("error"),
    ),
    /** Provider account/property identifier — never store tokens here. */
    externalId: v.optional(v.string()),
    connectedAt: v.optional(v.number()),
    lastSyncAt: v.optional(v.number()),
    error: v.optional(v.string()),
  })
    .index("by_organization", ["organizationId"])
    .index("by_organization_provider", ["organizationId", "provider"]),

  /**
   * Latest normalized report produced by either a cloud OAuth action or the
   * local Analyst agent. UI reads this instead of repeatedly hitting provider
   * APIs whenever the Analytics page renders.
   */
  analyticsSnapshot: defineTable({
    organizationId: v.string(),
    provider: v.string(),
    period: v.string(),
    activeUsers: v.optional(v.number()),
    sessions: v.optional(v.number()),
    pageViews: v.optional(v.number()),
    conversions: v.optional(v.number()),
    revenue: v.optional(v.number()),
    metricLabel: v.optional(v.string()),
    series: v.optional(
      v.array(v.object({ date: v.string(), value: v.number() })),
    ),
    rangeMetrics: v.optional(
      v.array(
        v.object({
          key: v.string(),
          period: v.string(),
          activeUsers: v.optional(v.number()),
          sessions: v.optional(v.number()),
          pageViews: v.optional(v.number()),
          conversions: v.optional(v.number()),
          revenue: v.optional(v.number()),
        }),
      ),
    ),
    capturedAt: v.number(),
  })
    .index("by_organization", ["organizationId"])
    .index("by_organization_provider", ["organizationId", "provider"]),

  /** In-flight OAuth authorization state for any provider's connect flow. */
  oauthState: defineTable({
    state: v.string(),
    organizationId: v.string(),
    provider: v.string(),
    createdAt: v.number(),
    consumedAt: v.optional(v.number()),
    status: v.union(
      v.literal("pending"),
      v.literal("connected"),
      v.literal("error"),
    ),
    error: v.optional(v.string()),
  }).index("by_state", ["state"]),

  /**
   * OAuth tokens per workspace and provider, for cloud-track connections.
   * Local-track connections keep credentials on the user's machine and never
   * write here. externalId/externalName carry the provider's primary object
   * (a GA4 property, an ad account, ...).
   */
  credential: defineTable({
    organizationId: v.string(),
    provider: v.string(),
    accessToken: v.string(),
    refreshToken: v.optional(v.string()),
    expiresAt: v.optional(v.number()),
    scope: v.optional(v.string()),
    externalId: v.optional(v.string()),
    externalName: v.optional(v.string()),
    accountName: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_organization_provider", ["organizationId", "provider"]),

  /**
   * Opaque credentials used by the local Executor control plane. The raw
   * capability is generated by the desktop app and stored only in Executor;
   * Convex keeps its SHA-256 digest so a database read cannot impersonate an
   * agent. Rotating the capability replaces the sole active row per workspace.
   */
  agentCapability: defineTable({
    organizationId: v.string(),
    tokenHash: v.string(),
    createdAt: v.number(),
    lastUsedAt: v.optional(v.number()),
  })
    .index("by_organization", ["organizationId"])
    .index("by_token_hash", ["tokenHash"]),

  /** User and workspace image uploads stored in Convex file storage. */
  imageAsset: defineTable({
    ownerId: v.string(),
    kind: v.union(v.literal("profile"), v.literal("workspace")),
    storageId: v.id("_storage"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_owner_kind", ["ownerId", "kind"])
    .index("by_storage", ["storageId"]),

  /**
   * Stripe billing state, scoped to the better-auth organization. The row is
   * created lazily at Checkout/Portal time so we can reuse one Stripe customer
   * per workspace before Stripe has emitted subscription webhooks.
   */
  subscription: defineTable({
    organizationId: v.string(),
    stripeCustomerId: v.string(),
    stripeSubscriptionId: v.optional(v.string()),
    status: v.union(
      v.literal("trialing"),
      v.literal("active"),
      v.literal("past_due"),
      v.literal("canceled"),
      v.literal("incomplete"),
    ),
    priceId: v.optional(v.string()),
    currentPeriodStart: v.optional(v.number()),
    currentPeriodEnd: v.optional(v.number()),
    trialEnd: v.optional(v.number()),
    cancelAtPeriodEnd: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_organization", ["organizationId"])
    .index("by_stripeCustomerId", ["stripeCustomerId"])
    .index("by_stripeSubscriptionId", ["stripeSubscriptionId"]),

  stripeWebhookEvent: defineTable({
    stripeEventId: v.string(),
    type: v.string(),
    processedAt: v.number(),
  }).index("by_stripeEventId", ["stripeEventId"]),
});
