import Foundation

actor PhoneWorkspaceSetupWorker {
  private let relay: any RelayServing
  private let credentials: InferenceCredentialStore
  private let session: URLSession

  init(
    relay: any RelayServing,
    credentials: InferenceCredentialStore,
    session: URLSession = .shared
  ) {
    self.relay = relay
    self.credentials = credentials
    self.session = session
  }

  func run(draft: OnboardingDraft, workspaceID: String) async throws {
    guard draft.runtime == .phone else { return }
    guard draft.inferenceProvider == .openCodeGo else {
      throw WorkspaceSetupError.unsupportedInference
    }
    print("[Chief] phone worker credential state: \(credentials.contains(.openCodeGo))")
    guard let lease = try await claim(workspaceID: workspaceID) else {
      throw WorkspaceSetupError.missingJob
    }
    print("[Chief] phone worker claimed \(lease.job.kind)")
    // The opening is generated by real inference only. There is no canned
    // fallback: if the agent cannot produce a genuine message, onboarding
    // surfaces the failure instead of fabricating a welcome line.
    let message = try await generatedOpeningMessage(draft: draft)
    print("[Chief] phone worker prepared opening (\(message.count) chars)")
    try await relay.completeAgentJob(
      workspaceID: workspaceID,
      agentID: "chief",
      leaseToken: lease.leaseToken,
      completion: AgentJobCompletion(
        openingMessage: message,
        publishedMessage: AgentPublishedMessage(
          conversationId: "mission-control",
          body: message
        )
      )
    )
    print("[Chief] phone worker completed \(lease.job.kind)")
  }

  private func claim(workspaceID: String) async throws -> AgentJobLease? {
    for attempt in 0..<3 {
      if let lease = try await relay.claimAgentJob(
        workspaceID: workspaceID,
        agentID: "chief"
      ) {
        return lease
      }
      if attempt < 2 { try await Task.sleep(for: .milliseconds(250)) }
    }
    return nil
  }

  private func generatedOpeningMessage(draft: OnboardingDraft) async throws -> String {
    try Task.checkCancellation()
    guard draft.inferenceProvider == .openCodeGo else {
      throw WorkspaceSetupError.unsupportedInference
    }
    guard let key = try credentials.load(.openCodeGo), !key.isEmpty else {
      throw WorkspaceSetupError.missingCredential
    }
    let endpoint = URL(string: "https://opencode.ai/zen/go/v1/chat/completions")!
    var request = URLRequest(url: endpoint)
    request.httpMethod = "POST"
    request.timeoutInterval = 60
    request.setValue("application/json", forHTTPHeaderField: "content-type")
    request.setValue("Bearer \(key)", forHTTPHeaderField: "authorization")
    request.httpBody = try JSONEncoder().encode(
      OpenCodeRequest(
        model: draft.inferenceModel,
        messages: [
          .init(
            role: "system",
            content: """
            You are Chief, a concise and proactive chief of staff. Write naturally and conversationally. Never use em dashes. Do not claim work has happened unless the supplied setup proves it. Return only the opening message.
            """
          ),
          .init(
            role: "user",
            content: """
            Start the mission-control channel for \(draft.companyName). The company website is \(draft.website.isEmpty ? "not supplied" : draft.website). The user selected these apps: \(draft.selectedApps.sorted().joined(separator: ", ")). Briefly confirm that the workspace is live, say what you will inspect first, and explain that relevant specialists will appear as useful work is identified. Keep it to 2 or 3 short sentences.
            """
          ),
        ],
        maxTokens: 220
      )
    )
    let (data, response) = try await session.data(for: request)
    guard let http = response as? HTTPURLResponse, (200..<300).contains(http.statusCode) else {
      throw WorkspaceSetupError.inferenceFailed
    }
    let output = try JSONDecoder().decode(OpenCodeResponse.self, from: data)
    guard
      let content = output.choices.first?.message.content,
      !content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    else {
      throw WorkspaceSetupError.inferenceFailed
    }
    return content
  }
}

enum WorkspaceSetupError: LocalizedError {
  case inferenceFailed
  case missingCredential
  case missingJob
  case unsupportedInference

  var errorDescription: String? {
    switch self {
    case .inferenceFailed: "Chief could not finish the first setup response. Try again."
    case .missingCredential: "Reconnect OpenCode Go to start Chief on this iPhone."
    case .missingJob: "Chief's setup job was not available. Try again."
    case .unsupportedInference: "This on-device model cannot run Chief yet."
    }
  }
}

struct OpenCodeRequest: Encodable {
    struct Message: Encodable {
        let role: String
        let content: String?
        let toolCalls: [ToolCall]?
        let toolCallID: String?

        init(
            role: String,
            content: String?,
            toolCalls: [ToolCall]? = nil,
            toolCallID: String? = nil
        ) {
            self.role = role
            self.content = content
            self.toolCalls = toolCalls
            self.toolCallID = toolCallID
        }

        enum CodingKeys: String, CodingKey {
            case role
            case content
            case toolCalls = "tool_calls"
            case toolCallID = "tool_call_id"
        }
    }

    struct ToolCall: Encodable {
        struct Function: Encodable {
            let name: String
            let arguments: String
        }
        let id: String
        let type: String
        let function: Function
    }

    struct ToolDefinition: Encodable {
        struct Function: Encodable {
            let name: String
            let description: String
            let parameters: [String: AnyEncodable]
        }
        let type: String
        let function: Function
    }

    let model: String
    let messages: [Message]
    let maxTokens: Int
    let tools: [ToolDefinition]?

    init(
        model: String,
        messages: [Message],
        maxTokens: Int,
        tools: [ToolDefinition]? = nil
    ) {
        self.model = model
        self.messages = messages
        self.maxTokens = maxTokens
        self.tools = tools
    }

    enum CodingKeys: String, CodingKey {
        case model, messages, tools
        case maxTokens = "max_tokens"
    }
}

struct OpenCodeResponse: Decodable {
    struct Choice: Decodable {
        struct Message: Decodable {
            struct ToolCall: Decodable {
                struct Function: Decodable {
                    let name: String
                    let arguments: String
                }
                let id: String
                let function: Function
            }
            let content: String?
            let toolCalls: [ToolCall]?

            enum CodingKeys: String, CodingKey {
                case content
                case toolCalls = "tool_calls"
            }
        }
        let message: Message
    }
    let choices: [Choice]
}

/// Bridges arbitrary JSON values into `Encodable` for tool schemas.
struct AnyEncodable: Encodable {
    let value: Any

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch value {
        case let int as Int: try container.encode(int)
        case let double as Double: try container.encode(double)
        case let bool as Bool: try container.encode(bool)
        case let string as String: try container.encode(string)
        case let array as [Any]: try container.encode(array.map(AnyEncodable.init(value:)))
        case let dict as [String: Any]: try container.encode(dict.mapValues { AnyEncodable(value: $0) })
        default: try container.encodeNil()
        }
    }
}
